export const Images = {
  viernesDeLocos: require("./viernesDeLocos.png"),
  homoArgentum: require("./homoArgentum.png"),
  liloYStitch: require("./liloYStitch.jpg"),
  gatillero: require("./Gatillero.png"),
  weapons: require("./weapons.png"),
  hotMilk: require("./HotMilk.png"),
  highestLowest: require("./HighestLowest.png"),
  materialists: require("./Materialists.png"),
  wrongParis: require("./WrongParis.png"),
  ballerina: require("./Ballerina.png"),
  frenchLover: require("./FrenchLover.png"),
  enemies: require("./Enemies.png"),
  deathOfUnicorn: require("./DeathOfUnicorn.png"),
  iKnowWhatYouDidLastSummer: require("./IKnowWhatYouDidLatSummer.png"),
  profilePlaceholder: require("./profile-placeholder.png"),
  fondoLogin: require("./imagen-fondo-login.jpg"),
  monstruo: require("./Monstruo.png"),
  batman: require("./batman.png"),
  vientosOscuros: require("./VientosOscuros.png"),
  veoveo: require("./veoveo.png"),
  header: require("./header.png"),
  robpattinson: require("./cast1.jpg"),
  hbo: require("./hbo.png"),
  netflix: require("./netflix.png"),
  amazon: require("./amazon.png"),
  fondo: require("./transparent-film-tape.png"),
 
};
